

all:
	$(MAKE) -C core
	$(MAKE) -C toolbox
	$(MAKE) -C explicit
	$(MAKE) -C predictor
	$(MAKE) -C solvers
	

clean:
	$(MAKE) clean -C core
	$(MAKE) clean -C toolbox
	$(MAKE) clean -C explicit
	$(MAKE) clean -C predictor
	$(MAKE) clean -C solvers
	